### ISSUE TITLE
card Duplicate issues  on viewing mode

### ISSUE THREAD

**Issue by imqipan** [web3go-xyz/web3go-xyz-v2#161]
In viewing mode, the card should not be capable of Duplicate.
在浏览模式下, card不应该显示Duplicate选项.

<img width="1266" alt="image" src="https://user-images.githubusercontent.com/3082172/223681199-fe32dae4-2b1a-4f0e-92a2-3d78337596aa.png">

**Comment by zhanggoodzhi** [comment]
done
