### ISSUE TITLE
MySpace Dashboard/Dataset Count in Tab is wrong

### ISSUE THREAD

**Issue by imqipan** [web3go-xyz/web3go-xyz-v2#183]
先前Dashboard和Dataset有All选项(包含Posted, Draft), 所以Tab上的数量默认统计的All, 但现在没有All了这样数据就不正确了
<img width="1174" alt="image" src="https://user-images.githubusercontent.com/3082172/224970773-6e342ac4-58bd-40aa-a6c7-397a216333e8.png">

复现gif:
![Mar-14-2023 18-26-48](https://user-images.githubusercontent.com/3082172/224972065-e0fdd93c-56aa-48c8-aa68-f2e2a3cfb13c.gif)

**Comment by zhanggoodzhi** [comment]
Done
