### ISSUE TITLE
should not follow myself

### ISSUE THREAD

**Issue by bianyunjian** [web3go-xyz/web3go-xyz-v2#189]
current user is  bianyunjian@web3go.xyz,
should not follow myself.
need to check all follow elements.

![Image](https://user-images.githubusercontent.com/12878885/225297999-0f2c51bb-2b1f-4be8-8c7e-21766f9d7b4d.png)

**Comment by imqipan** [comment]
improved in the backend! @zhanggoodzhi Exception handler in the front end is also needed(Loading is lingering).

<img width="842" alt="image" src="https://user-images.githubusercontent.com/3082172/225302528-21bf518d-fd2f-438b-b0b3-633d6f4aad3b.png">
