### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by trmaphi** [web3go-xyz/web3go-xyz-v2#211]
1.  When go into dashboard, if I'm the creator of the dashboard want a fast edit button (current I have to go to my space and click option to edit)
2. Add click to update filter in dashboard
3. Extend session, so I need sign in once in 7 days or 30 days
4. Able to click a column in chart to filter
5. Able to change visualization on dataset screen

**Comment by bianyunjian** [comment]
for 1  , design change isrequired.    won't support it in short time.

**Comment by bianyunjian** [comment]
for 3 , it's api access token grant issues,  by default configuration as 7 days.    not a  big deal for builders, even can sign in per day.

for viewers , it does not require for signin.

**Comment by bianyunjian** [comment]
for  2,4 , support


![Image](https://user-images.githubusercontent.com/12878885/233894309-5c0f188a-25f2-4804-9197-3943af17b72f.png)
