### ISSUE TITLE
V2-Share

### ISSUE THREAD

**Issue by bianyunjian** [web3go-xyz/web3go-xyz-v2#222]
目前的几个dashboard 是从后台直接制作的， 不是通过v2魔改后的界面

截图是在v2魔改后的界面，点击保存时会触发截图=》 share时使用该截图

临时解决方案：
在v2魔改后的前端界面上，进入对应dashboard的编辑页面， 点击保存， 此时会触发截图=》ok

**Comment by bianyunjian** [comment]
如何进入编辑界面：
MySpace=> dashboard edit

![Image](https://github.com/web3go-xyz/web3go-xyz-v2/assets/12878885/b0888dd1-b384-4909-b7c2-f1adaeb0dc46)

**Comment by bianyunjian** [comment]
save 触发截图


![Image](https://github.com/web3go-xyz/web3go-xyz-v2/assets/12878885/b96acfd9-a309-4f0c-92bc-fa2f30e5e626)

**Comment by bianyunjian** [comment]
解决方案：
1. 在后台编辑 dashboard时，界面上增加一个按钮： Set Preview ， 用于设置dashboard的预览图
2. 点击按钮后，出现modal dialog
3. 在modal dialog上 支持 上传一张图片，  并显示图片， 图片由开发者自己准备（截图或准备其他图片）
4. 确认后，调用api 保存图片为  dashboard.previewImg

**Comment by zhanggoodzhi** [comment]
Done.
