### ISSUE TITLE
Give the credential of the database of Moonbeam staking database

### ISSUE THREAD

**Issue by Moehringen** [web3go-xyz/web3go-xyz-v2#228]
Here is the background: I think letting the moonbeam team investigate themselves would be convenient for both. 

Please provide some explanation for the table if possible. 

![Image](https://github.com/web3go-xyz/web3go-xyz-v2/assets/45129082/a1d0bb3e-139d-43e6-85e0-5d82a6330fc2)

**Comment by trmaphi** [comment]
give two databases accesses with readonly

one from cumulon db
one from prod-moonbeam-staking db
