### ISSUE TITLE
Web3 Foundation Grant Program

### ISSUE THREAD

**Issue by bianyunjian** [web3go-xyz/web3go-xyz-v2#85]
if you could help with the docker file about V2, we could delivery it to Web3 Foundation following Grant Program.

Previous submit sample: https://github.com/Moehringen/Grant-Milestone-Delivery/blob/master/deliveries/Web3Go_milestone_1.md

This is the original application: https://github.com/w3f/Grants-Program/blob/master/applications/Web3Go.md

This is the guide on how to submit: https://github.com/w3f/Grant-Milestone-Delivery#mailbox-milestone-delivery-process

**Comment by happyJ2024** [comment]
**DONE**
